version: "3"

services:
  mysqldb:
    image: mysql
    restart: always
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    image: tayeb99/devops
    restart: always
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
volumes:
  db: