version: "3.8"

services:
  mysqldb:
    image: mysql
    restart: always
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./spring-app
    restart: always
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
volumes:
  db: